"use client"

import './globals.css'
import React from 'react';
import { neonCursor } from 'threejs-toys';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  React.useEffect(() => {
    neonCursor({
      el: document.getElementById('app'),
      shaderPoints: 16,
      curvePoints: 80,
      curveLerp: 0.5,
      radius1: 5,
      radius2: 30,
      velocityTreshold: 10,
      sleepRadiusX: 300,
      sleepRadiusY: 300,
      sleepTimeCoefX: 0.0025,
      sleepTimeCoefY: 0.0025
    })
  }, [])

  return (
    <html lang="en">
      <body id="app">{children}</body>
    </html>
  )
}
